global:

  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bekkerstacks'

rule_files:

  - 'alert.rules'

alerting:

scrape_configs:

  - job_name: 'mysql-exporter'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.mysql-exporter'
      type: 'A'
      port: 9104

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.traefik'
      type: 'A'
      port: 8080
