version: '3.7'

services:

  thumbor:
    image: "gperreymond/thumbor:6.7.0-alpine"
    networks:
      - private_thumbor
      - public
    environment:
      RESPECT_ORIENTATION: "True"
      USE_GIFSICLE_ENGINE: "True"
      LOADER: "tc_aws.loaders.s3_loader"
      TC_AWS_ENABLE_HTTP_LOADER: "True"
      TC_AWS_ALLOWED_BUCKETS: "['lalalab-products-source', 'lalalab-raw-files']"
      TC_AWS_REGION: "eu-west-1"
      AWS_ACCESS_KEY_ID: "..."
      AWS_SECRET_ACCESS_KEY: "..."
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.docker.network=public"
        - "traefik.port=8888"
        - "traefik.backend=thumbor"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:thumbor.docker.localhost"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.entryPoints=http,https"

networks:

  private_thumbor:
    driver: overlay
    name: private_thumbor
  public:
    external: true
